export {default as NotFound} from './NotFound'
export {default as Home} from './Home'
export {default as Contact} from './Contact'
export {default as About} from './About'
export {default as Career} from './Career'
export {default as Projects} from './Projects'